### ISSUE TITLE
Too much Calls

### ISSUE THREAD

**Issue by kamm0r** [viktak/ha-cc-openweathermap_all#10]
Hi, OpenWeather sent a mail with this text.
I suppose that >1000 calls per day are a lot (for my purpose) 
It is normal? How I can solve? Where is possible to limit the calls to (i.e.) 3 per hour?
###
One Call API usage alert
Dear Customer!
Thank you for choosing [OpenWeather](https://openweathermap.org/)!
We have noticed that your account is currently using [One Call API](https://openweathermap.org/api/one-call-api) quite intensively and exceed the account limit of 1000 calls per day. 
[cut]
###
thanks a lot

Marco alias Kamm0r

**Comment by viktak** [comment]
Hi, yes, I also got this notification this morning. Looking at it...

**Comment by viktak** [comment]
I pushed out a new version that **temporarily** uses a workaround:

1. Sets a 10 minute poll interval
2. Removes the UVI sensor (that caused the problem)

Everything else should work as expected.

I'll try to find a permanent fix soon. Until then I'll leave this issue open.

**Comment by nicocoetzee** [comment]
Ha, this is why....

**Comment by viktak** [comment]
Yepp, that explains a lot... :)

**Comment by viktak** [comment]
I just re-enabled 'onecall', so that UV values are also reported again.

I have been testing it overnight and it seems that the polling happens every 10 minutes or so. Each time it sends 3 queries to `api.openweathermap.org`. This means that on a regular day it will make 24*6*3=432 calls. This is well below the limit of `60 calls/minute` allowed by the [free plan](https://openweathermap.org/price) of OpenWeatherMaps.

For people who have their APIs temporarily blocked:
Please update your component to the latest, and the block should be lifted automatically after a day or so. If not (or don't want to wait), contact OpenWeatherMaps and ask for help doing so.
